name: 'Parse Simple Markdown Table'
description: 'Parses a simple markdown table into a JSON string.'
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'green'

# Define your inputs here.
inputs:
  markdown:
    description:
      'The markdown to parse, which should only contain a markdown table'
    required: true

# Define your outputs here.
outputs:
  result:
    description:
      'The JSON String of the parsed markdown table, or an empty string if it
      could not be parsed.'

runs:
  using: node20
  main: dist/index.js
